# Preparation {-}

## Packages {-}
```{r }
library(patchwork)
```

## Read and process simulation data {-}

```{r }
all_results <-
  readRDS(here("Shared/Results/all_results.rds")) %>%
  dplyr::select(scenario, sim_results) %>%
  unnest()
```

```{r }
eonr_data <-
  all_results %>%
  dplyr::select(scenario, exp_set_id, model, eonr_results) %>%
  unnest() %>%
  data.table() %>%
  .[, model := case_when(
    model == "rf" ~ "RF",
    model == "brf" ~ "BRF",
    model == "ma_cf" ~ "CF",
    model == "lm" ~ "OLS",
    model == "ser_50" ~ "SEM"
  )] %>%
  .[, model :=
    factor(
      model,
      levels = c("RF", "BRF", "CF", "OLS", "SEM")
    )]

perf_data <-
  all_results %>%
  dplyr::select(scenario, exp_set_id, model, performance) %>%
  unnest() %>%
  data.table() %>%
  .[, model := case_when(
    model == "rf" ~ "RF",
    model == "brf" ~ "BRF",
    model == "ma_cf" ~ "CF",
    model == "lm" ~ "OLS",
    model == "ser_50" ~ "SEM"
  )] %>%
  .[, model :=
    factor(
      model,
      levels = c("RF", "BRF", "CF", "OLS", "SEM")
    )] %>%
  .[, field_size := case_when(
    exp_set_id == 1 ~ "Small field",
    exp_set_id == 2 ~ "Medium field",
    exp_set_id == 3 ~ "Large field"
  )]
```

# Figures {-}

## Boxplot: Yield RMSE, EONR RMSE, and Profit Deficit {-}

```{r }
# /*===========================================================
#' # Boxplot: yield, EONR, profit combined
# /*===========================================================

g_perf_exp <-
  perf_data %>%
  nest_by(scenario, exp_set_id) %>%
  mutate(data = list(
    data.table(data) %>%
      .[, rmse_train := NULL] %>%
      melt(
        id.vars = c("model", "sim"),
        measure.vars = c("rmse_cv", "rmse_eonr", "profit")
      ) %>%
      .[, variable := case_when(
        variable == "rmse_cv" ~ "Yield RMSE (kg/ha)",
        variable == "rmse_eonr" ~ "EONR RMSE (kg/ha)",
        variable == "profit" ~ "Profit Deficit ($/ha)"
      )] %>%
      .[, variable :=
        factor(
          variable,
          levels = c(
            "Yield RMSE (kg/ha)",
            "EONR RMSE (kg/ha)",
            "Profit Deficit ($/ha)"
          )
        )]
  )) %>%
  mutate(g_performance = list(
    ggplot(data, aes(y = value, x = model, fill = model)) +
      stat_boxplot(
        geom = "errorbar",
        width = 0.4,
        position = position_dodge(0.6),
        lwd = 0.25
      ) +
      geom_boxplot(
        position = position_dodge(0.6),
        width = 0.4,
        outlier.shape = NA,
        lwd = 0.25
      ) +
      facet_wrap(. ~ variable, scales = "free_y") +
      ylab("") +
      xlab("") +
      theme_bw() +
      theme(
        legend.position = "none",
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm")
      )
  )) %>%
  dplyr::select(-data) %>%
  nest_by(scenario) %>%
  mutate(g_performance_all = list(
    (data$g_performance[[3]] + ggtitle("(A) Large field")) /
      (data$g_performance[[2]] + ggtitle("(B) Medium field")) /
      (data$g_performance[[1]] + ggtitle("(C) Small field"))
  ))

# g_perf_exp$g_performance_all[[1]]

saveRDS(g_perf_exp, "GitControlled/Writing/Figures/g_perf_exp.rds")
```

## Single simulation illustration: yield & EONR {-}

```{r }
# /*===========================================================
#' # Single simulation illustration: yield & EONR
# /*===========================================================
# fig.id = "single-simu-yield", "single-simu-EONR"
# fig.cap = "Illustration, single simulation"

sim_example <- 58
gdata <- aunit_data[sim == sim_example, ]
mean_dt <- gdata %>%
  .[, .(
    rmse_yield = mean((yield - yield_hat)^2, na.rm = TRUE) %>% sqrt() %>% round(1),
    rmse_EONR = mean((EONR - opt_N_hat)^2) %>% sqrt() %>% round(1),
    x_yield = quantile(yield, 0.05),
    y_yield = quantile(yield_hat, 0.99),
    x_EONR = quantile(EONR, 0.05),
    y_EONR = quantile(opt_N_hat, 0.99) + 15
  ),
  by = .(model)
  ] %>%
  print()

#* predicted vs true yield
single_simu_yield <-
  source(here("GitControlled", "Codes", "Modules", "figure_single_simu_yield.R"))$value
#* predicted vs true EONR
single_simu_EONR <-
  source(here("GitControlled", "Codes", "Modules", "figure_single_simu_EONR.R"))$value
```

## The distribution of the ratio of estimated EONR to true EONR {-}

```{r }
# /*===========================================================
#' # Ratio to True EONR
# /*===========================================================
# fig.id = "eonr-ratio-kernel",
# fig.cap = ""

field_pars_data <-
  readRDS(here("Shared/Data/all_sim_data.rds")) %>%
  #* assign aunit_id to cell id
  mutate(field_pars = list(
    field_pars %>%
      #--- True cell-level EONR ---#
      .[, opt_N := (pN / pCorn - b1) / (2 * b2)] %>%
      .[, opt_N := pmin(Nk, opt_N)] %>%
      .[, opt_N := pmax(0, opt_N)] %>%
      .[, .(sim, cell_id, opt_N)] %>%
      data.table(field_sf)[, .(cell_id, aunit_id)][., on = "cell_id"]
  )) %>%
  dplyr::select(exp_set_id, field_col, field_pars) %>%
  unnest() %>%
  data.table() %>%
  .[, .(exp_set_id, field_col, sim, cell_id, aunit_id, opt_N)] %>%
  .[, .(opt_N = mean(opt_N)), by = c("field_col", "exp_set_id", "sim", "aunit_id")]

g_eonr_ratio_all <-
  eonr_data %>%
  field_pars_data[., on = c("exp_set_id", "sim", "aunit_id")] %>%
  .[, field_size := case_when(
    exp_set_id == 1 ~ "Small field",
    exp_set_id == 2 ~ "Medium field",
    exp_set_id == 3 ~ "Large field"
  )] %>%
  #------ EONR_hat/EONR ratio for each aunit ------#
  .[, ratio := opt_N_hat / opt_N] %>%
  #------ average ratio for each simulation ------#
  .[, .(ratio = mean(ratio)), by = .(scenario, field_size, sim, model)] %>%
  nest_by(scenario) %>%
  mutate(g_eonr_ratio = list(
    #------ kernel density plot ------#
    ggplot(data = data) +
      geom_density(
        aes(x = ratio, color = model, fill = model),
        position = "identity",
        geom = "line",
        size = 0.5,
        alpha = 0.35
      ) +
      facet_wrap(field_size ~ ., ncol = 1) +
      # coord_cartesian(xlim = c(0.6, 1.5)) +
      xlim(0.6, 1.5) +
      xlab("Average Ratio of Estimated EONR to True EONR") +
      ylab("Density") +
      labs(color = "Model", fill = "Model") +
      theme_bw() +
      theme(
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.key.width = unit(0.75, "cm"),
        legend.text = element_text(margin = margin(r = 1, unit = "cm")),
        axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5),
        axis.text = element_text(color = "black")
      ) +
      guides(fill = guide_legend(
        label.position = "right",
        keywidth = unit(0.5, "cm"),
        keyheight = unit(0.5, "cm"),
        title.position = "left",
        title.vjust = 1
      ))
  ))

saveRDS(g_eonr_ratio_all, "GitControlled/Writing/Figures/g_eonr_ratio_all.rds")

# g_eonr_ratio_all$g_eonr_ratio[[3]]
```

## Treatment effect visualization 

## Compare acros scenarios for the large field {-}

```{r }
g_perf_across_scenarios <-
  perf_data %>%
  .[field_size == "Large field", ] %>%
  .[scenario %in% c("ideal", "complete", "non-linear"), ] %>%
  .[, scenario := factor(scenario, levels = c("ideal", "complete", "non-linear"))] %>%
  ggplot(., aes(y = profit, x = model, fill = model)) +
  stat_boxplot(
    geom = "errorbar",
    width = 0.4,
    position = position_dodge(0.6),
    lwd = 0.25
  ) +
  geom_boxplot(
    position = position_dodge(0.6),
    width = 0.4,
    outlier.shape = NA,
    lwd = 0.25
  ) +
  facet_wrap(. ~ scenario) +
  ylab("") +
  xlab("") +
  theme_bw() +
  theme(
    legend.position = "none",
    legend.title = element_blank(),
    legend.key.size = unit(0.4, "cm")
  )

saveRDS(g_perf_across_scenarios, "GitControlled/Writing/Figures/g_perf_across_scenarios.rds")
```
