# Preparation

```{r }
#* packages
library(sp)
library(spdep)
library(spatialreg)
library(sf)
library(glmnet)
library(raster)
library(data.table)
library(tidyverse)
library(dplyr)
library(parallel)
library(magrittr)
library(gstat)
library(GWmodel)
library(scam)
library(mgcv)
library(fixest)
library(magic)
library(stringr)
library(ggplot2)
library(tictoc)
library(here)
```

## Source all the R functions
```{r }
here("GitControlled", "Codes", "Functions", "R") %>%
  fs::dir_ls(., full.names = TRUE) %>%
  purrr::map(~ source(.))
```

## Read the simulation data

```{r }
all_sim_data <- readRDS(here("Shared/Data/all_sim_data.rds"))
```

# Simulation

## Specify which models to run

```{r }
#* select the estimation models you want
models_data <-
  tribble(
    ~model, ~on,
    "ser_50", TRUE, # spatial error 50m
    "ser_100", FALSE, # spatial error 100m
    "lm", TRUE, # OLS
    "ma_cf", TRUE, # multi-arm causal forest
    "brf", TRUE, # boosted regression forest
    "rf", TRUE, # random forest
    "dmlof_semi", FALSE, # DML orthogonal forest semiparametric
    "dmlof_quad", FALSE, # DML orthogonal forest quadratic
    "drof", FALSE, # Doubly-robust orthogonal forest
    "gwr_t", FALSE, # GWR Trevisan
    "gwr_semi", FALSE, # GWR semi-parametric (gam)
    "gwr_zone_scam", FALSE # GWR zoning and then gam
  ) %>%
  data.table()
```

## Specify variables to include

```{r }
x_vars <- c("Nk", "plateau", "b0")

x_vars <-
  c(
    "b0_1", "b0_2",
    # "b1_2_1", "b1_2_2", "b1_1_1", "b1_1_2",
    # "b2_2_1", "b2_2_2", "b2_1_1", "b2_1_2",
    "Nk_2_1", "Nk_2_2", "Nk_1_1", "Nk_1_2",
    "plateau_2_1", "plateau_2_2", "plateau_1_1", "plateau_1_2",
    "theta_plateau_2", "theta_Nk_2", "theta_b0_2"
  )

x_vars <-
  c(
    "b0_1",
    # "b0_2",
    # "b1_2_1", "b1_2_2", "b1_1_1", "b1_1_2",
    # "b2_2_1", "b2_2_2", "b2_1_1", "b2_1_2",
    "Nk_2_1", "Nk_2_2", "Nk_1_1",
    # "Nk_1_2",
    "plateau_2_1", "plateau_2_2", "plateau_1_1",
    # "plateau_1_2",
    "theta_plateau_2", "theta_Nk_2", "theta_b0_2"
  )

control_vars <- paste0(x_vars, collapse = "+")
int_vars <-
  paste0(
    paste0("I(N * ", x_vars, ")", collapse = "+"),
    "+",
    paste0("I(N2 * ", x_vars, ")", collapse = "+")
  )

feols_formula <-
  paste0(
    "yield ~ N + N2 + ",
    control_vars, "+",
    int_vars
  ) %>%
  formula()
```

## Run simulations

```{r }
# field_pars <- all_sim_data$field_pars[[1]]
# field_sf <- all_sim_data$field_sf[[1]]
# reg_data <- all_sim_data$reg_data[[1]]
# weights_matrix <- all_sim_data$weights_matrix[[1]]
# pN <- all_sim_data$pN[[1]]
# pCorn <- all_sim_data$pCorn[[1]]

nsim <- 1000

# all_results$sim_results[[1]]$performance[[2]]

all_results <-
  all_sim_data %>%
  .[3, ] %>%
  mutate(sim_results = list(
    get_eonr_by_exp_setting(
      sim_range = 1:100,
      models_data = models_data,
      x_vars = x_vars,
      field_pars = field_pars,
      field_sf = field_sf,
      reg_data = reg_data,
      weights_matrix = weights_matrix,
      pN = pN,
      pCorn = pCorn,
      nsim = nsim
    )
  )) %>%
  dplyr::select(exp_set_id, sim_results) %>%
  unnest()

saveRDS(
  all_results,
  here("Shared/Results/all_results_exp.rds")
)

all_results <- readRDS(here("Shared/Results/all_results_exp.rds"))
```

